// Generated by gencpp from file tfservice/exploreSrvResponse.msg
// DO NOT EDIT!


#ifndef TFSERVICE_MESSAGE_EXPLORESRVRESPONSE_H
#define TFSERVICE_MESSAGE_EXPLORESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tfservice
{
template <class ContainerAllocator>
struct exploreSrvResponse_
{
  typedef exploreSrvResponse_<ContainerAllocator> Type;

  exploreSrvResponse_()
    : position()
    , hard_stop(false)  {
    }
  exploreSrvResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , hard_stop(false)  {
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _position_type;
  _position_type position;

   typedef uint8_t _hard_stop_type;
  _hard_stop_type hard_stop;




  typedef boost::shared_ptr< ::tfservice::exploreSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tfservice::exploreSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct exploreSrvResponse_

typedef ::tfservice::exploreSrvResponse_<std::allocator<void> > exploreSrvResponse;

typedef boost::shared_ptr< ::tfservice::exploreSrvResponse > exploreSrvResponsePtr;
typedef boost::shared_ptr< ::tfservice::exploreSrvResponse const> exploreSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tfservice::exploreSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tfservice::exploreSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tfservice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tf2_msgs': ['/opt/ros/indigo/share/tf2_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tfservice::exploreSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfservice::exploreSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfservice::exploreSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df50e939898a4f5d8ed2d6b044afe211";
  }

  static const char* value(const ::tfservice::exploreSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf50e939898a4f5dULL;
  static const uint64_t static_value2 = 0x8ed2d6b044afe211ULL;
};

template<class ContainerAllocator>
struct DataType< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tfservice/exploreSrvResponse";
  }

  static const char* value(const ::tfservice::exploreSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] position\n\
bool hard_stop\n\
";
  }

  static const char* value(const ::tfservice::exploreSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.hard_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct exploreSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tfservice::exploreSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tfservice::exploreSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "hard_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hard_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TFSERVICE_MESSAGE_EXPLORESRVRESPONSE_H
