// Generated by gencpp from file tfservice/globalSrvResponse.msg
// DO NOT EDIT!


#ifndef TFSERVICE_MESSAGE_GLOBALSRVRESPONSE_H
#define TFSERVICE_MESSAGE_GLOBALSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tfservice
{
template <class ContainerAllocator>
struct globalSrvResponse_
{
  typedef globalSrvResponse_<ContainerAllocator> Type;

  globalSrvResponse_()
    : updated(false)
    , theta(0.0)
    , position()  {
    }
  globalSrvResponse_(const ContainerAllocator& _alloc)
    : updated(false)
    , theta(0.0)
    , position(_alloc)  {
    }



   typedef uint8_t _updated_type;
  _updated_type updated;

   typedef float _theta_type;
  _theta_type theta;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _position_type;
  _position_type position;




  typedef boost::shared_ptr< ::tfservice::globalSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tfservice::globalSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct globalSrvResponse_

typedef ::tfservice::globalSrvResponse_<std::allocator<void> > globalSrvResponse;

typedef boost::shared_ptr< ::tfservice::globalSrvResponse > globalSrvResponsePtr;
typedef boost::shared_ptr< ::tfservice::globalSrvResponse const> globalSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tfservice::globalSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tfservice::globalSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tfservice

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'tf2_msgs': ['/opt/ros/indigo/share/tf2_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tfservice::globalSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tfservice::globalSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfservice::globalSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tfservice::globalSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfservice::globalSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tfservice::globalSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tfservice::globalSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f892ab4eaf0c16a33839e99c96d74ef6";
  }

  static const char* value(const ::tfservice::globalSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf892ab4eaf0c16a3ULL;
  static const uint64_t static_value2 = 0x3839e99c96d74ef6ULL;
};

template<class ContainerAllocator>
struct DataType< ::tfservice::globalSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tfservice/globalSrvResponse";
  }

  static const char* value(const ::tfservice::globalSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tfservice::globalSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool updated\n\
float32 theta\n\
float32[] position\n\
";
  }

  static const char* value(const ::tfservice::globalSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tfservice::globalSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.updated);
      stream.next(m.theta);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct globalSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tfservice::globalSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tfservice::globalSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "updated: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.updated);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TFSERVICE_MESSAGE_GLOBALSRVRESPONSE_H
