// Generated by gencpp from file tfservice/globalSrv.msg
// DO NOT EDIT!


#ifndef TFSERVICE_MESSAGE_GLOBALSRV_H
#define TFSERVICE_MESSAGE_GLOBALSRV_H

#include <ros/service_traits.h>


#include <tfservice/globalSrvRequest.h>
#include <tfservice/globalSrvResponse.h>


namespace tfservice
{

struct globalSrv
{

typedef globalSrvRequest Request;
typedef globalSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct globalSrv
} // namespace tfservice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tfservice::globalSrv > {
  static const char* value()
  {
    return "fe3632406195713ff0da2cbdf8e828bf";
  }

  static const char* value(const ::tfservice::globalSrv&) { return value(); }
};

template<>
struct DataType< ::tfservice::globalSrv > {
  static const char* value()
  {
    return "tfservice/globalSrv";
  }

  static const char* value(const ::tfservice::globalSrv&) { return value(); }
};


// service_traits::MD5Sum< ::tfservice::globalSrvRequest> should match 
// service_traits::MD5Sum< ::tfservice::globalSrv > 
template<>
struct MD5Sum< ::tfservice::globalSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::globalSrv >::value();
  }
  static const char* value(const ::tfservice::globalSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::globalSrvRequest> should match 
// service_traits::DataType< ::tfservice::globalSrv > 
template<>
struct DataType< ::tfservice::globalSrvRequest>
{
  static const char* value()
  {
    return DataType< ::tfservice::globalSrv >::value();
  }
  static const char* value(const ::tfservice::globalSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tfservice::globalSrvResponse> should match 
// service_traits::MD5Sum< ::tfservice::globalSrv > 
template<>
struct MD5Sum< ::tfservice::globalSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::globalSrv >::value();
  }
  static const char* value(const ::tfservice::globalSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::globalSrvResponse> should match 
// service_traits::DataType< ::tfservice::globalSrv > 
template<>
struct DataType< ::tfservice::globalSrvResponse>
{
  static const char* value()
  {
    return DataType< ::tfservice::globalSrv >::value();
  }
  static const char* value(const ::tfservice::globalSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TFSERVICE_MESSAGE_GLOBALSRV_H
