// Generated by gencpp from file tfservice/ImuSrv.msg
// DO NOT EDIT!


#ifndef TFSERVICE_MESSAGE_IMUSRV_H
#define TFSERVICE_MESSAGE_IMUSRV_H

#include <ros/service_traits.h>


#include <tfservice/ImuSrvRequest.h>
#include <tfservice/ImuSrvResponse.h>


namespace tfservice
{

struct ImuSrv
{

typedef ImuSrvRequest Request;
typedef ImuSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuSrv
} // namespace tfservice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tfservice::ImuSrv > {
  static const char* value()
  {
    return "d41085fd9e23edf9efb8c5d896ef9228";
  }

  static const char* value(const ::tfservice::ImuSrv&) { return value(); }
};

template<>
struct DataType< ::tfservice::ImuSrv > {
  static const char* value()
  {
    return "tfservice/ImuSrv";
  }

  static const char* value(const ::tfservice::ImuSrv&) { return value(); }
};


// service_traits::MD5Sum< ::tfservice::ImuSrvRequest> should match 
// service_traits::MD5Sum< ::tfservice::ImuSrv > 
template<>
struct MD5Sum< ::tfservice::ImuSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::ImuSrv >::value();
  }
  static const char* value(const ::tfservice::ImuSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::ImuSrvRequest> should match 
// service_traits::DataType< ::tfservice::ImuSrv > 
template<>
struct DataType< ::tfservice::ImuSrvRequest>
{
  static const char* value()
  {
    return DataType< ::tfservice::ImuSrv >::value();
  }
  static const char* value(const ::tfservice::ImuSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tfservice::ImuSrvResponse> should match 
// service_traits::MD5Sum< ::tfservice::ImuSrv > 
template<>
struct MD5Sum< ::tfservice::ImuSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::ImuSrv >::value();
  }
  static const char* value(const ::tfservice::ImuSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::ImuSrvResponse> should match 
// service_traits::DataType< ::tfservice::ImuSrv > 
template<>
struct DataType< ::tfservice::ImuSrvResponse>
{
  static const char* value()
  {
    return DataType< ::tfservice::ImuSrv >::value();
  }
  static const char* value(const ::tfservice::ImuSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TFSERVICE_MESSAGE_IMUSRV_H
