// Generated by gencpp from file tfservice/NuSrv.msg
// DO NOT EDIT!


#ifndef TFSERVICE_MESSAGE_NUSRV_H
#define TFSERVICE_MESSAGE_NUSRV_H

#include <ros/service_traits.h>


#include <tfservice/NuSrvRequest.h>
#include <tfservice/NuSrvResponse.h>


namespace tfservice
{

struct NuSrv
{

typedef NuSrvRequest Request;
typedef NuSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NuSrv
} // namespace tfservice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tfservice::NuSrv > {
  static const char* value()
  {
    return "a8d9d17b37b0c9a4256566443542d8f5";
  }

  static const char* value(const ::tfservice::NuSrv&) { return value(); }
};

template<>
struct DataType< ::tfservice::NuSrv > {
  static const char* value()
  {
    return "tfservice/NuSrv";
  }

  static const char* value(const ::tfservice::NuSrv&) { return value(); }
};


// service_traits::MD5Sum< ::tfservice::NuSrvRequest> should match 
// service_traits::MD5Sum< ::tfservice::NuSrv > 
template<>
struct MD5Sum< ::tfservice::NuSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::NuSrv >::value();
  }
  static const char* value(const ::tfservice::NuSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::NuSrvRequest> should match 
// service_traits::DataType< ::tfservice::NuSrv > 
template<>
struct DataType< ::tfservice::NuSrvRequest>
{
  static const char* value()
  {
    return DataType< ::tfservice::NuSrv >::value();
  }
  static const char* value(const ::tfservice::NuSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tfservice::NuSrvResponse> should match 
// service_traits::MD5Sum< ::tfservice::NuSrv > 
template<>
struct MD5Sum< ::tfservice::NuSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::NuSrv >::value();
  }
  static const char* value(const ::tfservice::NuSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::NuSrvResponse> should match 
// service_traits::DataType< ::tfservice::NuSrv > 
template<>
struct DataType< ::tfservice::NuSrvResponse>
{
  static const char* value()
  {
    return DataType< ::tfservice::NuSrv >::value();
  }
  static const char* value(const ::tfservice::NuSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TFSERVICE_MESSAGE_NUSRV_H
