// Generated by gencpp from file tfservice/tfSrv.msg
// DO NOT EDIT!


#ifndef TFSERVICE_MESSAGE_TFSRV_H
#define TFSERVICE_MESSAGE_TFSRV_H

#include <ros/service_traits.h>


#include <tfservice/tfSrvRequest.h>
#include <tfservice/tfSrvResponse.h>


namespace tfservice
{

struct tfSrv
{

typedef tfSrvRequest Request;
typedef tfSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct tfSrv
} // namespace tfservice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tfservice::tfSrv > {
  static const char* value()
  {
    return "fe3632406195713ff0da2cbdf8e828bf";
  }

  static const char* value(const ::tfservice::tfSrv&) { return value(); }
};

template<>
struct DataType< ::tfservice::tfSrv > {
  static const char* value()
  {
    return "tfservice/tfSrv";
  }

  static const char* value(const ::tfservice::tfSrv&) { return value(); }
};


// service_traits::MD5Sum< ::tfservice::tfSrvRequest> should match 
// service_traits::MD5Sum< ::tfservice::tfSrv > 
template<>
struct MD5Sum< ::tfservice::tfSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::tfSrv >::value();
  }
  static const char* value(const ::tfservice::tfSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::tfSrvRequest> should match 
// service_traits::DataType< ::tfservice::tfSrv > 
template<>
struct DataType< ::tfservice::tfSrvRequest>
{
  static const char* value()
  {
    return DataType< ::tfservice::tfSrv >::value();
  }
  static const char* value(const ::tfservice::tfSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tfservice::tfSrvResponse> should match 
// service_traits::MD5Sum< ::tfservice::tfSrv > 
template<>
struct MD5Sum< ::tfservice::tfSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tfservice::tfSrv >::value();
  }
  static const char* value(const ::tfservice::tfSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tfservice::tfSrvResponse> should match 
// service_traits::DataType< ::tfservice::tfSrv > 
template<>
struct DataType< ::tfservice::tfSrvResponse>
{
  static const char* value()
  {
    return DataType< ::tfservice::tfSrv >::value();
  }
  static const char* value(const ::tfservice::tfSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TFSERVICE_MESSAGE_TFSRV_H
